Repository guzzle/guzzle, pull requests merged in 2020-09, with the labels that each got.

#2712 Avoid "functions" from dependencies
  CHANGELOG.md
  composer.json
  docs/psr7.rst
  docs/quickstart.rst
  docs/request-options.rst
  src/Client.php
  src/Exception/RequestException.php
  src/Handler/CurlFactory.php
  src/Handler/CurlMultiHandler.php
  src/Handler/MockHandler.php
  src/Handler/StreamHandler.php
  src/MessageFormatter.php
  src/Middleware.php
  src/Pool.php
  src/PrepareBodyMiddleware.php
  src/RedirectMiddleware.php
  src/RetryMiddleware.php
  tests/Exception/RequestExceptionTest.php
  tests/Handler/CurlFactoryTest.php
  tests/Handler/CurlHandlerTest.php
  tests/Handler/CurlMultiHandlerTest.php
  tests/Handler/MockHandlerTest.php
  tests/Handler/StreamHandlerTest.php
  tests/InternalUtilsTest.php
  tests/MessageFormatterTest.php
  tests/MiddlewareTest.php
  tests/PrepareBodyMiddlewareTest.php
  tests/RedirectMiddlewareTest.php
Labels: Keep open

#2660 Pass response to TooManyRedirectsException
  src/RedirectMiddleware.php
  tests/RedirectMiddlewareTest.php
Labels: Keep open, Review wanted

#2591 Handle exceptions during response creation
  src/Handler/CurlFactory.php
  src/Handler/EasyHandle.php
  tests/Handler/CurlFactoryTest.php
  tests/Server.php
Labels: Keep open, Review wanted, kind/bug
